[package]
name = "ansa"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils = { version = "0.8", optional = true }

[dev-dependencies]
rand = "0.8.5"

[features]
cache-padded = ["crossbeam-utils"]
